### ISSUE TITLE
TypeError: r.users.remove is not a function

### ISSUE THREAD

**Issue by astrex1969** [Juby210/discord.js-reaction-menu#9]
new rm.menu({
    channel: message.channel,
    userID: message.author.id,
    pages: ['test', 'test2', 'test3']
})

**Comment by Juby210** [comment]
Are you using discord.js v12.x?

**Comment by astrex1969** [comment]
oops i was using v11 ,i updated it and its working now , sorry to bother you.

**Comment by astrex1969** [comment]
> 
> 
> Are you using discord.js v12.x?
